apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.id }}
spec:
  serviceName: zk-service
  replicas: 1
  selector: 
    matchLabels: 
      app: zk-quorum
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: zk-quorum
    spec:
      affinity:
      {{- if .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zk-quorum
            topologyKey: kubernetes.io/hostname
      {{- end }}
      serviceAccountName: zk-sa
      containers:
        - name: zk-pod
          imagePullPolicy: Always
          image: {{ .Values.image }}
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
