---
title: "Installation"
format: html
---

Magasin is an scalable end-to-end data platform based on open-source components that is natively run in a [kubernetes cluster](https://kubernetes.io).

Kubernetes is a container orchestration system designed to automate the deployment, scaling, and management of [containerized applications](https://kubernetes.io/docs/concepts/overview/#going-back-in-time). It is an integral part of services offered by major cloud providers. Kubernetes, being open source, can also be set up on-premises. For testing purposes, it is even possible to install it on a desktop computer.

Magasin uses Kubernetes in combination with [Helm](https://helm.sh/), a package manager for Kubernetes applications. Helm is the equivalent to apt, pip, npm, pacman, snap, conda.. Using Helm, users specify the configuration of required Kubernetes resources to deploy magasin through a values file or command-line overrides. A package in helm is called **chart**.

Magasin includes an installer script that sets up all the necessary dependencies on your computer, enabling the seamless setup of within the Kubernetes cluster.


#  Deploy magasin using the installer (beta)

Once you have access to a kubernetes cluster, you can use the installer to setup magasin in that cluster. 

The major goal of this installer is to ease the setup of some tools that need to be installed in your computer, and then deploy magasin in the kubernetes cluster and th

The installer is in beta, in case it fails check the [troubleshooting section](troubleshooting.qmd), or try the [manual installation section](#manual-installation)


* **Deploying magasin from a Debian/Like GNU/Linux computer**

    ```bash
    curl -X https://unicef.github.io/magasin/install-magasin.sh | bash
    ```

  Debian like distributions are Ubuntu, Raspbian, Kali Linux, etc. They use `apt-get` as package manager.  

* **Deploying magasin from a MacOS computer**

  ```bash
  curl -X https://unicef.github.io/magasin/install-magasin.sh | zsh
  ```

In both cases, if You need a user that can run sudo.

* **Deploying magasin from a Windows computer**
  Please use the [manual installation](manual-installation.qmd)

## Advanced use of the magasin-installer

You can check the options.
```bash
./install-magasin.sh -h
Usage: install-magasin.sh [-y] [-c] [-r realm_prefix-realm_postfix (magasin)] [-d] [-h]

This script checks dependencies and installs magasin components
Each component is installed within its own namespace.

Options:
  -y  Skip prompting questions during installation
  -c  Only check if all pre-requisites are installed.
  -r  Realm prefix and suffix (default: magasin).
      If more than one '-', the last one will be used as separator.
      The realm 'magasin-new-dev' will set 'magasin-new' as prefix and 'dev' as suffix.
      
  -d  Enable debug mode (displays all commands run).
  -h  Display this help message and exit.
```

Examples of usage:

1.  Only check if all the required components are installed

      ```sh
        install-magasin.sh -c 
      ```

2.  Setup the realm test-. Will use test-<component> as namespace.
    Setup the realm magasin-dev. Will use magasin-<component>-dev as namespaces

      ```sh
        install-magasin.sh -r test
      ```


# Manual installation

If for some reason the installation scripts do not work for you, or your system is not covered by them, you can install all requirements manually manually.

1. [Install kubectl](https://kubernetes.io/docs/tasks/tools/)
2. [Install helm](https://helm.sh/docs/intro/install/)
3. [Install Python/pip](https://www.python.org/downloads/)

Ensure `kubectl` is pointing to the right kubernetes cluster

```sh
kubectl cluster-info
```

Add the magasin helm repo
```sh
helm repo add https://unicef.github.io/magasin/
```
Update the magasin helm repo
```sh
helm repo update magasin
```

Install the different helm charts (dagster, drill, superset, daskhub)

```sh
# helm install <component> magasin/<component> --namespace magasin-<component> --create-namespace
helm install dagster magasin/dagster --namespace magasin-dagster --create-namespace
helm install drill magasin/drill --namespace magasin-drill --create-namespace
helm install superset magasin/superset --namespace magasin-superset --create-namespace
helm install daskhub magasin/daskhub --namespace magasin-daskhub --create-namespace
```



