---
title: "About"
format: html
---

## About Magasin

Magasin (pronounced /ma.ɡa.zɛ̃/) is an end-to-end set of mature open-source toolset that enables organizations to unlock the full potential of their data driving digital transformation effortessly. 

Magasin enables data teams to seamlessly extract, analyze, and visualize data from multiple sources. 

Magasin takes flexibility to another level, thanks to its loosely coupled [architecture](architecture.qmd) composed by mature open-source tools. 

Magasin was created by [UNICEF](https://www.unicef.org) and since 2024, magasin is a [Digital Public Good (DPG)](https://github.com/unicef/magasin/discussions/103).


## Brief history 

Magasin grew out of Office of Innovation's and Information and Communication Technology Division (ICTD) work to establish a [RapidPro](https://www.rapidpro.io) Data Warehouse to enable aggregation of global metrics across vendor instances.

Also informed by experiences of the [Magic Box](https://www.unicef.org/innovation/Magicbox) applied data science initiative, a range of components were evaluated and trialed with country offices to arrive at the current components and architecture.

In 2021, ICTD engaged one of its long term agreement with a vendor to assist with evolving the proof-of-concept into a minimum viable product (MVP).

In 2023, UNICEF ICTD Digital Center of Excellence (DCOE) started the journey to detach _magasin_ from its organizational and cloud infrastructure dependencies, and release it as an open-source platform with the aim helping to attain the [Sustainable Development Goals (SDGs)](./sdgs.qmd) and to create a more equitable world.

On [February 2nd](https://en.wikipedia.org/wiki/Groundhog_Day_(film)),2024, UNICEF released magasin as an [open source](https://github.com/unicef/magasin) solution. This release ships with an an [easy to install process](install/) toolkit as well as [how to get started documentation](get-started/).

On the [31st of October 2024](https://en.wikipedia.org/wiki/Halloween), magasin was declared a [Digital Public Good](https://github.com/unicef/magasin/discussions/103) by the [Digital Public Goods Alliance](https://app.digitalpublicgoods.net/a/11177).





